name: Unit Test

on:
  workflow_dispatch

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup project
        run: cat package.json
      - name: Setup project
        run: npm ci
